const DEVICE_ID_PATTERN = /^[0-9a-f]{64}$/

/** Lowercased device ID for the account payload; empty means the generated device. */
export function normalizeClaudeDeviceId(value: string): string {
  return value.trim().toLowerCase()
}

/** Empty is valid and keeps the device generated by the gateway. */
export function isClaudeDeviceId(value: string): boolean {
  const normalized = normalizeClaudeDeviceId(value)
  return normalized === '' || DEVICE_ID_PATTERN.test(normalized)
}

/** Only Anthropic OAuth and setup-token accounts send a Claude Code device ID. */
export function supportsClaudeDeviceId(platform?: string, type?: string): boolean {
  return platform === 'anthropic' && (type === 'oauth' || type === 'setup-token')
}
